version: '3.0'

services:
  php:
    build:
      context: .docker/php
    restart: always
    container_name: php
    volumes:
      - ./:/app
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db
    networks:
      - symfony_app

  nginx:
    build:
      context: .docker/nginx
    volumes:
      - ./:/app
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - symfony_app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - symfony_app

networks:
  symfony_app:
#    driver: bridge
#volumes:
###> doctrine/doctrine-bundle ###
#  database_data:
###< doctrine/doctrine-bundle ###
